ioBroker/adapter-react-v5

- src/Components/TreeTable.js
I fixed a few bugs in the TreeTable and also solved a problem I had opened
and also added a number field to the numeric field.
I noticed these when I wanted to integrate the TreeTable into ioBroker-React from AlCalzone
```
error in der Console:
Warning: Each child in a list should have a unique "key" prop.
Warning: Received `true` for a non-boolean attribute `contained`.
```
> I have fixed a few errors in the TreeTable

- src/Dialogs/TextInput.js
causes https://github.com/ioBroker/ioBroker.admin/issues/2053
> fix icon import of TextDialog

- schemas/jsonConfig.json
- schemas/testJsonConfig.json
closes #183
closes #184
closes #185
closes #186 
closes #187
> Schema improvements

- schemas/jsonConfig.json
- schemas/testJsonConfig.json
added alive and cron components
added `doNotSave` to checkbox and password
> Schema improve

- schemas/jsonConfig.json
- schemas/testJsonConfig.json
closes #197 
closes #198
closes #199
closes #200
closes #201
>  added uk to translation and added iconPosition for panel and more schema improvements

- schemas/jsonConfig.json
- schemas/testJsonConfig.json
closes #207 
closes #205 
closes #204 
closes #192
> Schema fixes

- schemas/jsonConfig.json
- schemas/testJsonConfig.json
> fix schema for autocompleteSendTo

- README.md
- src/Components/ColorPicker.js
- src/Components/FileBrowser.js
- see https://github.com/ioBroker/ioBroker.vis-2/issues/127
> fixed light mode color of path in FileBrowser 

- schemas/jsonConfig.json
- schemas/testJsonConfig.json
> adapt schema for table object ids

- schemas/jsonConfig.json
- schemas/testJsonConfig.json
- test/testSchema.ts
> added fileSelector to schema

- schemas/jsonConfig.json
- schemas/testJsonConfig.json
- see https://github.com/ioBroker/ioBroker.admin/pull/2245/files
> added json config sendTo onLoaded

- schemas/jsonConfig.json
- schemas/testJsonConfig.json
- test/testSchema.ts
- tsconfig.build.json
> added noInternal to ip schema

- schemas/jsonConfig.json
- schemas/testJsonConfig.json
> fix schema for objectId component

- schemas/jsonConfig.json
- schemas/testJsonConfig.json
- test/testSchema.ts
> add accordion to schema

- schemas/jsonConfig.json
- schemas/testJsonConfig.json
> added color for static link

- schemas/jsonConfig.json
- schemas/testJsonConfig.json
- test/testSchema.ts
see https://github.com/ioBroker/ioBroker.admin/pull/2552
> added qrCode component to schema

- schemas/jsonConfig.json
- schemas/testJSONConfigPanel.json
- test/testSchema.ts
> add deviceManager to schema

- README.md
- package.json
* (bluefox) Added translations
> [OFFICIAL RELEASE] 6.1.8

- schemas/jsonConfig.json
- schemas/testJsonConfig.json
closes #387 
and specify specific file name for `#include`
> added missing table base props to chips and autocomplete

- README.md
- package.json
* (bluefox) Updated JSON schema
> [OFFICIAL RELEASE] 6.1.9

- README.md
- package.json
* (bluefox) Updated the object browser
> [OFFICIAL RELEASE] 6.1.10

- README.md
- package.json
* (bluefox) Showed the context menu under cursor position in the object browser
* (bluefox) Added links to aliases in the object browser
> [OFFICIAL RELEASE] 7.0.2

- package.json
-   (bluefox) Updated socket classes
> chore: release v7.1.2

- README.md
- package.json
-   (@GermanBluefox) Small layout change for Icon Picker
> [OFFICIAL RELEASE] 7.2.2
